# Generated by Django 4.0.2 on 2024-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_medicalhistory_tonus_medicalhistory_visus_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='doctor',
        ),
        migrations.AddField(
            model_name='visit',
            name='doctor',
            field=models.ManyToManyField(to='registration.Doctor'),
        ),
    ]
